site_name: FROG
repo_url: https://github.com/ImperialCollegeLondon/FROG
watch: [frog]

theme:
  name: "material"

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: "¤"

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            merge_init_into_class: true
          paths: [frog]

nav:
  - FROG documentation: index.md
  - User guide: user_guide.md
  - Hardware: hardware.md
  - Hardware sets: hardware_sets.md
  - Measure scripts: measure_scripts.md
  - DECADES: decades.md
  # defer to gen-files + literate-nav
  - Code Reference: reference/
