name: Test and build

on:
  push:
    branches: [main]
  pull_request:
  release:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: poetry run pytest --cov-report=xml

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && success()
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Check documentation builds correctly
        if: matrix.os == 'ubuntu-latest'
        uses: ./.github/actions/build-docs

      - name: Build exe
        if: matrix.os == 'windows-latest'
        uses: ./.github/actions/build-win-exe

      - uses: actions/upload-artifact@v4
        if: success() && matrix.os == 'windows-latest'
        with:
          name: FINESSE
          path: dist/FINESSE.exe
