name: Release
on:
  release:

jobs:
  upload_exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: "3.13"
      - uses: ./.github/actions/build-win-exe

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/FROG.exe
